'use client';

import { Sparkles } from 'lucide-react';

interface AIGenerationProgressProps {
  completed: number;
  total: number;
  className?: string;
}

const AIGenerationProgress = ({ completed, total, className = '' }: AIGenerationProgressProps) => {
  // Calculate percentage
  const percentage = total > 0 ? (completed / total) * 100 : 0;

  return (
    <div className={`flex items-center gap-4 ${className}`}>
      {/* Icon and Text */}
      <div className='flex items-center gap-2'>
        <Sparkles className='w-4 h-4 text-violet-600' />
        <p className='text-xs text-gray-600 font-normal whitespace-nowrap'>
          {completed}/{total} answers generated by AI
        </p>
      </div>

      {/* Progress Bar */}
      <div className='relative w-[220px] h-[6px]'>
        {/* Background */}
        <div className='absolute inset-0 bg-gray-200 rounded-full' />

        {/* Progress Fill */}
        <div
          className='absolute inset-y-0 left-0 bg-violet-600 rounded-full transition-all duration-300'
          style={{ width: `${percentage}%` }}
        />
      </div>
    </div>
  );
};

export default AIGenerationProgress;
